### ISSUE TITLE
"could not parse input as TOML" when using [patch]

### ISSUE THREAD

**Issue by stevenroose** [alexcrichton/cargo-vendor#148]
`Cargo.toml` (redacted)
```toml
[package]
name = "xx"

[dependencies]
log = "0.4.5"
bitcoin = "0.15"
bitcoin-bech32 = "0.8"
hid = "0.3"
secp256k1 = "0.11"
protobuf = "2.0"
byteorder = "1.2"
hex = "0.3.2"
unicode-normalization = "0.1.7"

[dev-dependencies]
fern = "0.5.6"

[patch.crates-io]
bitcoin = { path = "/path/to/bitcoin" }
```
